check-time: 99
message-delay: 5
maximum-allowed-violation-level: 150
commands-run:
  - 'ban %player AutoBanned by CONSOLE for using auto soup hacks!'
logging:
  enabled: false
  always: false
  if-level-divisible-by: 5
  at-level: 50